
services:
  nginx:
    image: nginx:1.27-alpine
    container_name: listos_nginx
    ports:
      - "80:80"
    volumes:
      - ./back:/var/www/html/back
      - /front/dist/listos:/var/www/html/front/dist/listos
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - listos_net

  php:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: listos_php
    volumes:
      - ./back:/var/www/html
    environment:
      - APP_ENV=dev
    networks:
      - listos_net

  postgres:
    image: postgres:15-alpine
    container_name: listos_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - listos_net

  angular:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: listos_front
    ports:
      - "4200:4200"
    volumes:
      - ./front:/app
      - /app/node_modules
    networks:
      - listos_net

networks:
  listos_net:

volumes:
  db_data:
